name: Build and Release tmux (macOS arm64)

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          brew install automake pkg-config curl

      - name: Run static build script (auto-confirm)
        run: |
          mkdir -p ~/install
          mkdir -p ~/build
          chmod +x ./build.sh
          echo y | ./build.sh ~/install ~/build

      - name: Package tmux binary
        run: |
          mkdir -p dist
          cp ~/install/tmux/bin/tmux dist/tmux-macos-arm64-${{ github.ref_name }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/tmux-macos-arm64-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
